name: Authentication Testing

on: [push, pull_request]

jobs:
  build-test:
    name: Testing User Authentication Service 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node dependencies and Running Test Cases.
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}      
      - run: npm ci
      - run: npm run test