name: Authentication Testing

on: [push, pull_request]

jobs:
  build-test:
    name: Testing User Authentication Service 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker-compose --version

      - name: Docker compose set all service up.
        run: docker-compose up -d

      - name: Install Node dependencies.
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}      
      - run: npm ci

      - name: Running Test Cases
        uses: actions/setup-node@v3
      - run: npm run test 
